<?php

/**
 * TDProject_Channel
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

// load the download URL from the Request
$downloadUrl = $this->getRequest()
    ->getAttribute(TDProject_Channel_Controller_Util_WebRequestKeys::DOWNLOAD_URL);

// check if the requested file is available, if yes, download it
if (file_exists($downloadUrl)) {
	header('Content-Description: File Transfer');
	header('Content-Type: application/octet-stream');
	header('Content-Disposition: attachment; filename=' . basename($downloadUrl));
	header('Content-Transfer-Encoding: binary');
	header('Expires: 0');
	header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
	header('Pragma: public');
	header('Content-Length: ' . filesize($downloadUrl));
	readfile($downloadUrl);
}