DROP TABLE IF EXISTS `release`;

CREATE TABLE `release` (
    `release_id` int(10) NOT NULL, 
    `package_id_fk` int(10) NOT NULL, 
    `version` varchar(25) NOT NULL,
    `stability` enum('devel','alpha','beta','stable') NOT NULL,
    `dependencies` text NULL,
    `package_file` text NULL,
    `package_size` int(10),
    `licence` varchar(25),
    `licence_uri` varchar(255),
    `short_description` varchar(255),
    `description` text,
    `release_date` int(10) NOT NULL,
    `notes` text
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ENGINE=MyISAM;

ALTER TABLE `release` ADD CONSTRAINT release_pk PRIMARY KEY (`release_id`); 
ALTER TABLE `release` CHANGE release_id `release_id` int(10) AUTO_INCREMENT;

CREATE INDEX release_idx_01 ON `release` (`package_id_fk`);

ALTER TABLE `release` ADD CONSTRAINT release_fk_01 FOREIGN KEY (`package_id_fk`) REFERENCES `package` (`package_id`) ON DELETE CASCADE;

ALTER TABLE `channel` ADD UNIQUE `channel_uidx_01` ( `alias` );
ALTER TABLE `channel` ADD UNIQUE `channel_uidx_02` ( `name` );

ALTER TABLE `channel` 
	ADD `create_package` TINYINT( 1 ) NULL DEFAULT '0',
	ADD `allowed_networks` VARCHAR( 255 ) NULL,
	ADD `allowed_ips` VARCHAR( 255 ) NULL;
	
ALTER TABLE `maintainer` 
    ADD `hash` VARCHAR( 32 ) NULL DEFAULT '',
    ADD `username` VARCHAR( 45 ) NULL DEFAULT '';
    
INSERT INTO `resource` (`resource_locale`, `key`, `message`) VALUES
('de_DE', 'page.navigation.root.channel', 'Channel'),
('de_DE', 'page.navigation.root.channel.channel', 'Channel'),
('de_DE', 'page.navigation.root.channel.category', 'Kategorien'),
('de_DE', 'page.navigation.root.channel.package', 'Package'),
('de_DE', 'title.channel.view', 'Channel bearbeiten'),
('de_DE', 'title.channel.overview', 'Channels'),
('de_DE', 'title.category.view', 'Kategorie bearbeiten'),
('de_DE', 'title.category.overview', 'Kategorien'),
('de_DE', 'title.package.view', 'Package bearbeiten'),
('de_DE', 'title.package.overview', 'Packages');
	
INSERT INTO `resource` (`resource_locale`, `key`, `message`) VALUES
('en_US', 'page.navigation.root.channel', 'Channels'),
('en_US', 'page.navigation.root.channel.channel', 'Channels'),
('en_US', 'page.navigation.root.channel.category', 'Categories'),
('en_US', 'page.navigation.root.channel.package', 'Packages'),
('en_US', 'title.channel.view', 'Edit Channel'),
('en_US', 'title.channel.overview', 'Channels'),
('en_US', 'title.category.view', 'Edit Category'),
('en_US', 'title.category.overview', 'Categories'),
('en_US', 'title.package.view', 'Edit Package'),
('en_US', 'title.package.overview', 'Packages');   
	
INSERT INTO `resource` (`resource_locale`, `key`, `message`) VALUES
('de_DE', 'page.content.tabs.channel', 'Channel'),
('de_DE', 'page.content.tabs.channel.grid.header.row.channelId', 'ID'),
('de_DE', 'page.content.tabs.channel.grid.header.row.name', 'Name'),
('de_DE', 'page.content.tabs.channel.grid.header.row.alias', 'Alias'),
('de_DE', 'page.content.tabs.channel.grid.header.row.summary', 'Kurzbeschreibung'),
('de_DE', 'page.content.tabs.channel.grid.header.row.actions', 'Actions'),
('de_DE', 'page.content.tabs.channel.grid.footer.row.channelId', 'ID'),
('de_DE', 'page.content.tabs.channel.grid.footer.row.name', 'Name'),
('de_DE', 'page.content.tabs.channel.grid.footer.row.alias', 'Alias'),
('de_DE', 'page.content.tabs.channel.grid.footer.row.summary', 'Kurzbeschreibung'),
('de_DE', 'page.content.tabs.channel.grid.footer.row.actions', 'Actions'),
('de_DE', 'page.content.tabs.channel.channel', 'Channel Daten'),
('de_DE', 'page.content.tabs.channel.channel.name', 'Name'),
('de_DE', 'page.content.tabs.channel.channel.alias', 'Alias'),
('de_DE', 'page.content.tabs.channel.channel.summary', 'Beschreibung'),
('de_DE', 'page.content.tabs.category', 'Kategorie'),
('de_DE', 'page.content.tabs.category.grid.header.row.categoryId', 'ID'),
('de_DE', 'page.content.tabs.category.grid.header.row.name', 'Name'),
('de_DE', 'page.content.tabs.category.grid.header.row.alias', 'Alias'),
('de_DE', 'page.content.tabs.category.grid.header.row.description', 'Beschreibung'),
('de_DE', 'page.content.tabs.category.grid.header.row.actions', 'Actions'),
('de_DE', 'page.content.tabs.category.grid.footer.row.categoryId', 'ID'),
('de_DE', 'page.content.tabs.category.grid.footer.row.name', 'Name'),
('de_DE', 'page.content.tabs.category.grid.footer.row.alias', 'Alias'),
('de_DE', 'page.content.tabs.category.grid.footer.row.description', 'Beschreibung'),
('de_DE', 'page.content.tabs.category.grid.footer.row.actions', 'Actions'),
('de_DE', 'page.content.tabs.category.category', 'Kategorie Daten'),
('de_DE', 'page.content.tabs.category.category.name', 'Name'),
('de_DE', 'page.content.tabs.category.category.alias', 'Alias'),
('de_DE', 'page.content.tabs.category.category.description', 'Beschreibung'),
('de_DE', 'page.content.tabs.package', 'Paket'),
('de_DE', 'page.content.tabs.package.grid.header.row.packageId', 'ID'),
('de_DE', 'page.content.tabs.package.grid.header.row.name', 'Name'),
('de_DE', 'page.content.tabs.package.grid.header.row.licence', 'Lizenz'),
('de_DE', 'page.content.tabs.package.grid.header.row.description', 'Beschreibung'),
('de_DE', 'page.content.tabs.package.grid.header.row.actions', 'Actions'),
('de_DE', 'page.content.tabs.package.grid.footer.row.packageId', 'ID'),
('de_DE', 'page.content.tabs.package.grid.footer.row.name', 'Name'),
('de_DE', 'page.content.tabs.package.grid.footer.row.licence', 'Lizenz'),
('de_DE', 'page.content.tabs.package.grid.footer.row.description', 'Beschreibung'),
('de_DE', 'page.content.tabs.package.grid.footer.row.actions', 'Actions'),
('de_DE', 'page.content.tabs.package.package', 'Package Daten'),
('de_DE', 'page.content.tabs.package.package.name', 'Name'),
('de_DE', 'page.content.tabs.package.package.licence', 'Lizenz'),
('de_DE', 'page.content.tabs.package.package.description', 'Beschreibung'),
('de_DE', 'page.content.tabs.package.package.deprecated', 'Deprecated'),
('de_DE', 'page.content.tabs.package.package.deprecatedChannel', 'Channel'),
('de_DE', 'page.content.tabs.package.package.deprecatedPackage', 'Package'),
('de_DE', 'page.content.tabs.package.package.channelIdFk', 'Channel'),
('de_DE', 'page.content.tabs.package.package.categoryIdFk', 'Kategorie'),
('de_DE', 'page.content.tabs.package.package.licenceUrl', 'Lizenz URI'),
('de_DE', 'page.content.tabs.package.package.shortDescription', 'Kurzbeschreibung'),
('de_DE', 'page.content.tabs.package.deprecated', 'Deprecated'),
('de_DE', 'page.content.tabs.package.deprecated.deprecated', 'Deprecated'),
('de_DE', 'page.content.tabs.package.deprecated.deprecatedChannel', 'Channel'),
('de_DE', 'page.content.tabs.package.deprecated.deprecatedPackage', 'Package'),
('de_DE', 'page.content.tabs.package.package.licenceUri', 'Lizenz URI'),
('de_DE', 'page.content.tabs.channel.upload', 'Upload Release'),
('de_DE', 'page.content.tabs.channel.upload.release', 'Release'),
('de_DE', 'page.content.tabs.release', 'Releases'),
('de_DE', 'page.content.tabs.release.releaseGrid.header.row.releaseId', 'ID'),
('de_DE', 'page.content.tabs.release.releaseGrid.header.row.version', 'Version'),
('de_DE', 'page.content.tabs.release.releaseGrid.header.row.licence', 'Lizenz'),
('de_DE', 'page.content.tabs.release.releaseGrid.header.row.stability', 'Stabilität'),
('de_DE', 'page.content.tabs.release.releaseGrid.header.row.shortDescription', 'Kurzbeschreibung'),
('de_DE', 'page.content.tabs.release.releaseGrid.header.row.actions', 'Actions'),
('de_DE', 'page.content.tabs.release.releaseGrid.footer.row.releaseId', 'ID'),
('de_DE', 'page.content.tabs.release.releaseGrid.footer.row.version', 'Version'),
('de_DE', 'page.content.tabs.release.releaseGrid.footer.row.licence', 'Lizenz'),
('de_DE', 'page.content.tabs.release.releaseGrid.footer.row.stability', 'Stabilität'),
('de_DE', 'page.content.tabs.release.releaseGrid.footer.row.shortDescription', 'Kurzbeschreibung'),
('de_DE', 'page.content.tabs.release.releaseGrid.footer.row.actions', 'Actions'),
('de_DE', 'page.content.tabs.channel.channel.createPackage', 'Paket anlegen wenn nicht vorhanden'),
('de_DE', 'page.content.tabs.channel.authorization', 'Authrisierung'),
('de_DE', 'page.content.tabs.channel.authorization.allowedNetworks', 'Berechtigte Netzwerke (Komma getrennt)'),
('de_DE', 'page.content.tabs.channel.authorization.allowedIps', 'Berechtigte IP''s (Komma getrennt)');

INSERT INTO `resource` (`resource_locale`, `key`, `message`) VALUES
('en_US', 'page.content.tabs.channel', 'Channel'),
('en_US', 'page.content.tabs.channel.grid.header.row.channelId', 'ID'),
('en_US', 'page.content.tabs.channel.grid.header.row.name', 'Name'),
('en_US', 'page.content.tabs.channel.grid.header.row.alias', 'Alias'),
('en_US', 'page.content.tabs.channel.grid.header.row.summary', 'Summary'),
('en_US', 'page.content.tabs.channel.grid.header.row.actions', 'Actions'),
('en_US', 'page.content.tabs.channel.grid.footer.row.channelId', 'ID'),
('en_US', 'page.content.tabs.channel.grid.footer.row.name', 'Name'),
('en_US', 'page.content.tabs.channel.grid.footer.row.alias', 'Alias'),
('en_US', 'page.content.tabs.channel.grid.footer.row.summary', 'Summary'),
('en_US', 'page.content.tabs.channel.grid.footer.row.actions', 'Actions'),
('en_US', 'page.content.tabs.channel.channel', 'Channel Data'),
('en_US', 'page.content.tabs.channel.channel.name', 'Name'),
('en_US', 'page.content.tabs.channel.channel.alias', 'Alias'),
('en_US', 'page.content.tabs.channel.channel.summary', 'Summary'),
('en_US', 'page.content.tabs.category', 'Category'),
('en_US', 'page.content.tabs.category.grid.header.row.categoryId', 'ID'),
('en_US', 'page.content.tabs.category.grid.header.row.name', 'Name'),
('en_US', 'page.content.tabs.category.grid.header.row.alias', 'Alias'),
('en_US', 'page.content.tabs.category.grid.header.row.description', 'Description'),
('en_US', 'page.content.tabs.category.grid.header.row.actions', 'Actions'),
('en_US', 'page.content.tabs.category.grid.footer.row.categoryId', 'ID'),
('en_US', 'page.content.tabs.category.grid.footer.row.name', 'Name'),
('en_US', 'page.content.tabs.category.grid.footer.row.alias', 'Alias'),
('en_US', 'page.content.tabs.category.grid.footer.row.description', 'Description'),
('en_US', 'page.content.tabs.category.grid.footer.row.actions', 'Actions'),
('en_US', 'page.content.tabs.category.category', 'Category Data'),
('en_US', 'page.content.tabs.category.category.name', 'Name'),
('en_US', 'page.content.tabs.category.category.alias', 'Alias'),
('en_US', 'page.content.tabs.category.category.description', 'Description'),
('en_US', 'page.content.tabs.package', 'Package'),
('en_US', 'page.content.tabs.package.grid.header.row.packageId', 'ID'),
('en_US', 'page.content.tabs.package.grid.header.row.name', 'Name'),
('en_US', 'page.content.tabs.package.grid.header.row.licence', 'Licence'),
('en_US', 'page.content.tabs.package.grid.header.row.description', 'Description'),
('en_US', 'page.content.tabs.package.grid.header.row.actions', 'Actions'),
('en_US', 'page.content.tabs.package.grid.footer.row.packageId', 'ID'),
('en_US', 'page.content.tabs.package.grid.footer.row.name', 'Name'),
('en_US', 'page.content.tabs.package.grid.footer.row.licence', 'Licence'),
('en_US', 'page.content.tabs.package.grid.footer.row.description', 'Description'),
('en_US', 'page.content.tabs.package.grid.footer.row.actions', 'Actions'),
('en_US', 'page.content.tabs.package.package', 'Package Data'),
('en_US', 'page.content.tabs.package.package.name', 'Name'),
('en_US', 'page.content.tabs.package.package.licence', 'Licence'),
('en_US', 'page.content.tabs.package.package.description', 'Description'),
('en_US', 'page.content.tabs.package.package.deprecated', 'Deprecated'),
('en_US', 'page.content.tabs.package.package.deprecatedChannel', 'Channel'),
('en_US', 'page.content.tabs.package.package.deprecatedPackage', 'Package'),
('en_US', 'page.content.tabs.package.package.channelIdFk', 'Channel'),
('en_US', 'page.content.tabs.package.package.categoryIdFk', 'Category'),
('en_US', 'page.content.tabs.package.package.licenceUrl', 'Licence URI'),
('en_US', 'page.content.tabs.package.package.shortDescription', 'Short Description'),
('en_US', 'page.content.tabs.package.deprecated', 'Deprecated'),
('en_US', 'page.content.tabs.package.deprecated.deprecated', 'Deprecated'),
('en_US', 'page.content.tabs.package.deprecated.deprecatedChannel', 'Channel'),
('en_US', 'page.content.tabs.package.deprecated.deprecatedPackage', 'Package'),
('en_US', 'page.content.tabs.package.package.licenceUri', 'Licence URI'),
('en_US', 'page.content.tabs.channel.upload', 'Upload Release'),
('en_US', 'page.content.tabs.channel.upload.release', 'Release'),
('en_US', 'page.content.tabs.release', 'Releases'),
('en_US', 'page.content.tabs.release.releaseGrid.header.row.releaseId', 'ID'),
('en_US', 'page.content.tabs.release.releaseGrid.header.row.version', 'Version'),
('en_US', 'page.content.tabs.release.releaseGrid.header.row.licence', 'Licence'),
('en_US', 'page.content.tabs.release.releaseGrid.header.row.stability', 'Stability'),
('en_US', 'page.content.tabs.release.releaseGrid.header.row.shortDescription', 'Short Description'),
('en_US', 'page.content.tabs.release.releaseGrid.header.row.actions', 'Actions'),
('en_US', 'page.content.tabs.release.releaseGrid.footer.row.releaseId', 'ID'),
('en_US', 'page.content.tabs.release.releaseGrid.footer.row.version', 'Version'),
('en_US', 'page.content.tabs.release.releaseGrid.footer.row.licence', 'Licence'),
('en_US', 'page.content.tabs.release.releaseGrid.footer.row.stability', 'Stability'),
('en_US', 'page.content.tabs.release.releaseGrid.footer.row.shortDescription', 'Short Description'),
('en_US', 'page.content.tabs.release.releaseGrid.footer.row.actions', 'Actions'),
('en_US', 'page.content.tabs.channel.channel.createPackage', 'Create package if not available'),
('en_US', 'page.content.tabs.channel.authorization', 'Authorization'),
('en_US', 'page.content.tabs.channel.authorization.allowedNetworks', 'Allowed networks (comma separated)'),
('en_US', 'page.content.tabs.channel.authorization.allowedIps', 'Allowed IP''s (comma separated)');